title: Ahmad A'fif
email: ahmadafif.personal@gmail.com
twitter_username: _cryst4lliz3
github_username: cryst4lliz3
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kuala_Lumpur

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ahmad A'fif bin Zulkifli"
  avatar : "/assets/images/me.jpg"
  bio    : "item happens ..."
  links:
    - label: "cryst4lliz3.github.io"
      icon: "fas fa-fw fa-link"
      url: "https://cryst4lliz3.github.io/"
    - label: "_cryst4lliz3"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_cryst4lliz3"
    - label: "cryst4lliz3"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cryst4lliz3/"

footer:
  links:
    - label: "_cryst4lliz3"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_cryst4lliz3"
    - label: "cryst4lliz3"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cryst4lliz3/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
